from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from pydantic import BaseModel
from openai import OpenAI
from typing import Optional
from geopy.geocoders import Nominatim
import base64
import os
import json
import httpx
import math

load_dotenv()

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)
geolocator = Nominatim(user_agent="PinnicalGeoLocator")
client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1",
)
AIModel = "meta-llama/llama-4-scout-17b-16e-instruct" # pov 2 hours later finding an actual model that works FINALLY
categoryTags = { # tags generated by claude ai
    "restaurant": '[amenity~"restaurant|cafe|fast_food|food_court|bar"]',
    "hospital":   '[amenity~"hospital|clinic|doctors|pharmacy"]',
    "hotel":      '[tourism~"hotel|motel|hostel|guest_house"]',
    "school":     '[amenity~"school|university|college|library"]',
    "gas":        '[amenity~"fuel|charging_station"]',
    "shopping":   '[shop]',
    "park":       '[leisure~"park|garden|playground"]',
    "bank":       '[amenity~"bank|atm"]',
    "gym":        '[leisure~"fitness_centre|sports_centre"]',
    "transit":    '[amenity~"bus_station|ferry_terminal"][railway~"station|halt"]',
}

# helper functions
def haversine(lat1, lon1, lat2, lon2): # with the power of google and searching up how to filter our locations we got this
    earthRadius = 6371000
    
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    
    deltaPhi = math.radians(lat2 - lat1)
    deltaLambda = math.radians(lon2 - lon1)
    
    a = math.sin(deltaPhi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(deltaLambda / 2) ** 2
    
    return earthRadius * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a)) # the shortest distance between two points on earth 

@app.get("/")
def root(): # js to check if the backend server didnt explode or something
    return {"message": "Backend is live"}

@app.post("/analyze")
async def analyzeImage(
    file: UploadFile = File(...),
    latitude: Optional[float] = Form(None),
    longitude: Optional[float] = Form(None)
):
    imageBytes = await file.read()
    imageBase64 = base64.b64encode(imageBytes).decode("utf-8")
    
    locationAddress = None
    
    if latitude and longitude:
        try:
            reversedGeo = geolocator.reverse(f"{latitude}, {longitude}")
            locationAddress = reversedGeo.address
        except Exception as e:
            print(f"Error with reversing coordinates: {e}")
    
    # claude generated ai prompt for our model
    prompt = f"""Analyze this image and return ONLY a valid JSON object with no extra text, no markdown, no backticks. Use this exact structure:
    {{
    "scene_type": "one of: urban, suburban, rural, wilderness, coastal, industrial, historical, mixed",
    "culture": "cultural region or influence visible",
    "historical_context": "brief historical or cultural significance",
    "description": "2-3 sentence description of the scene",
    "weather": "current weather conditions visible",
    "flora_fauna": ["list", "of", "visible", "plants", "or", "animals"],
    "confidence": 85
    }}
    {f'The image was taken at coordinates: {latitude}, {longitude} ({locationAddress}).' if locationAddress else ''}
    Respond with only the JSON, nothing else."""
    
    try:
        response = client.chat.completions.create(
            model = AIModel,
            max_tokens = 1024,
            messages = [{
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{imageBase64}"}}
                ],
            }]
        )
        
        rawResponse = response.choices[0].message.content.strip()
        
        # if its not already in plain text then filter out the extra symbols to make it parseable
        if rawResponse.startswith("```"):
            rawResponse = rawResponse.split("```")[1]
            if rawResponse.startswith("json"):
                rawResponse = rawResponse[4:]
        
        rawResponse = rawResponse.strip()
        
        analysis = json.loads(rawResponse)
        analysis["location"] = locationAddress or "Unknown"
        
        return analysis
    except json.JSONDecodeError as e:
        print(f"Unable to decode JSON: {e}")
        
        return {
            "error": "Failed to parse the model's response",
            "sceneType": "Unknown",
            "culture": "Unknown",
            "historicalContext": "Unknown",
            "description": "Failed the analysis",
            "weather": "Unknown",
            "floraFauna": [],
            "confidence": 0,
            "location": locationAddress or "Unknown"
        }
    except Exception as e:
        print(f"AI Model error: {e}")
        
        return {"error": str(e), "location": locationAddress or "Unknown"}

class ChatRequest(BaseModel):
    message: str
    imageBase64: str | None = None

@app.post("/ai-chat")
def AIChat(req: ChatRequest):
    messages = [{
        "role": "system", # claude ai generated prompt for our model
        "content": """You are an AI assistant built into Pinnical, a collaborative map app where users drop pins at real-world locations with photos. Each pin has an image, a location, and AI-generated scene analysis.
        When the user has set a pin as context, you have access to its coordinates and any available address/scene data. If given coordinates, you should be able to identify the general area or city they correspond to. When asked about location, give the address first and coordinates as a secondary detail if useful.
        Be concise and conversational. Only bring up the image or location details if the user asks about them."""
    }]
    
    if req.imageBase64:
        messages.append({
            "role": "user",
            "content": [
                {"type": "text", "text": req.message},
                {"type": "image_url", "image_url": {"url": req.imageBase64}}
            ]
        })
    else:
        messages.append({"role": "user", "content": req.message})
        
    completion = client.chat.completions.create(
        model = AIModel,
        max_tokens = 512, # half tokens than analyze since users will be chatting a lot more
        messages = messages
    )

    text = completion.choices[0].message.content or ""
    
    if not text.strip():
        return {"response": "Sorry, I couldn't generate a response. Please try again."}
        
    return {"response": text.strip()}

class ServiceRequest(BaseModel):
    message: str
    latitude: float
    longitude: float

@app.post("/service-pins")
async def servicePins(req: ServiceRequest):
    
    # first we need to check if the user is asking about services
    classifyPrompt = client.chat.completions.create(
        model = AIModel,
        max_tokens = 100,
        messages = [
            {
                "role": "system", # claude ai generated prompt for our model
                "content": """You are a classifier. Given a user message, determine if they are asking for nearby services or places (restaurants, hospitals, hotels, gas stations, shops, parks, banks, gyms, transit, schools, etc.).
                Respond ONLY with valid JSON, no extra text:
                {"is_service_query": true, "category": "restaurant"}
                Category must be one of: restaurant, hospital, hotel, school, gas, shopping, park, bank, gym, transit.
                If not a service query: {"is_service_query": false, "category": null}"""
            }, 
            {
                "role": "user",
                "content": req.message
            }
        ]
    )
    
    rawResponse = classifyPrompt.choices[0].message.content.strip()
    
    # if we cant get a result or the result says its not a service related question then simply return false and no pins
    try:
        result = json.loads(rawResponse)
    except json.JSONDecodeError:
        return {"is_service_query": False, "pins": []}
    
    if not result.get("is_service_query"):
        return {"is_service_query": False, "pins": []}       

    
    # proceeds if it is a service related question
    radius = 16093 # 10mi radius, hard coded for now but maybe also let the user change this?
    category = result.get("category", "restaurant")
    tag = categoryTags.get(category, '[amenity]')
    

    # test query with: https://overpass-turbo.eu/
    # api doc cuz im stupid: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL
    overpassQuery = f"""
    [out:json][timeout:25];
    (
    node{tag}(around:{radius},{req.latitude},{req.longitude});
    );
    out center 50;
    """
    
    # debgugging cuz the results are like to the left/below the pin?
    print(f"Searching around: {req.latitude}, {req.longitude} radius: {radius}m")
    print(f"Overpass query: {overpassQuery}")
    
    # https://fastapi.tiangolo.com/advanced/async-tests/#in-detail
    # httpx the best with fast api im pretty sure so we're using this ig
    try:
        async with httpx.AsyncClient(timeout = 15) as http:
            resp = await http.post(
                "https://overpass-api.de/api/interpreter",
                content=overpassQuery.encode(),
                headers={
                    "Content-Type": "application/x-www-form-urlencoded",
                    "User-Agent": "Pinnical",
                }
            )
            resp.raise_for_status() # check if successful
            data = resp.json()
    except Exception as e:
        print(f"Error with Overpass: {e}")
        return {"is_service_query": True, "pins": [], "error": "Could not look up location"}
    
    pins = []
    
    # insert all possible pins that have existing name/latitude/longitude
    for element in data.get("elements", []):
        tags = element.get("tags", {})
        name = tags.get("name")
        
        if not name:
            continue
        
        latitude = element.get("lat") or element.get("center", {}).get("lat")
        longitude = element.get("lon") or element.get("center", {}).get("lon")
        
        if not latitude or not longitude:
            continue
            
        address = ", ".join(filter(None, [
            tags.get("addr:housenumber", "") + " " + tags.get("addr:street", ""),
            tags.get("addr:city", ""),
            tags.get("addr:state", ""),
        ])).strip(", ")
        
        pins.append({
            "name":     name,
            "latitude": latitude,
            "longitude": longitude,
            "category": category,
            "address":  address or None,
        })
        
    print(f"pins: {pins}")
    
    pins.sort(key=lambda p: haversine(req.latitude, req.longitude, p["latitude"], p["longitude"]))
    
    return {"is_service_query": True, "category": category, "pins": pins[:15]}
        
            

    
